name: Deploy

# Trigger the workflow on push and 
# pull request events on the production branch
on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - production
      
# env:
#   api_gh_secret: ${{ secrets.TMDBKEY }}

# Authenticate to the the server via ssh 
# and run our deployment script 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env var
        run: |
          echo "api_gh_secret=${{ secrets.TMDBKEY }}" >> $GITHUB_ENV
      - name: Check previously set env var
        run: |
          echo "${{ env.api_gh_secret }}"
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /var/www/travellist && .scripts/deploy.sh"
